import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import RainbowKitContexts from "./src/BE/web3/Rainbowkit/RaibowkitProvider";
import Navbar from "./src/FE/navbar/Navbar";

const gilroySemiBold = localFont({
  src: "./fonts/gilroy-semibold.ttf",
  variable: "--font-gilroy-sb",
  weight: "900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gilroySemiBold.variable}  antialiased  `}>
        <RainbowKitContexts>
          <Navbar />
          {children}
        </RainbowKitContexts>
      </body>
    </html>
  );
}
